### ISSUE TITLE
Erro de digitação no nome?

### ISSUE THREAD

**Issue by Tuba2** [Samuel-Schlemper-Schlemuel/SingWriter#1]
O nome aparece escrito várias vezes como SingWriter, com Sing ("cantar") em vez de Sign ("sinal" ou "sinalizar"), inclusive no nome do repositório e do app no Flathub.

A ideia é mesmo manter essa grafia? Ou foi um erro de digitação?

Se for um erro, posso ajudar na revisão pra checar todas as instâncias em que isso aparece 😉

**Comment by Samuel-Schlemper-Schlemuel** [comment]
Olá! Obrigado por ter avisado isso, foi de fato um erro de digitação, mas não se preocupe com isso, conheço bem o programa e consigirei arruma-lo com velocidade, deve estar saindo a atualização com a correção hoje de noite ou amanhã de manhã

**Comment by Samuel-Schlemper-Schlemuel** [comment]
Lancei um novo app com o nome correto (infelizmento não dava de atualizar o app original pois isso envolveu também uma atualização de ID), estou tentando redirecionar o aplicativo antigo para o novo ou até apagalo de vez do flathub, mas acho que com essa atualização já é possível fechar este erro
